In [83]:
import cv2
import numpy as np
from anyio import sleep
from matplotlib import pyplot as plt
import imutils

In [84]:
card = cv2.imread('./card/digitalCard.jpg')
template = cv2.imread('./card/digitalTemplate.jpg')
card = cv2.cvtColor(card, cv2.COLOR_BGR2GRAY)
template = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)


In [85]:
_, card_t = cv2.threshold(card, 127, 255, cv2.THRESH_BINARY_INV)

In [86]:
contours_c, hierarchy_c = cv2.findContours(card_t, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)


In [87]:
_, template_t = cv2.threshold(template, 127, 255, cv2.THRESH_BINARY)

contours_t, hierarchy_t = cv2.findContours(template_t, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)



In [88]:
filtered_contours = []
x_min, y_min, x_max, y_max = 0, 100, 600, 250
for cnt in contours_c:
    area = cv2.contourArea(cnt)
    points = cnt.reshape(-1, 2)
    if np.all((points[:, 0] >= x_min) & (points[:, 0] <= x_max) &
              (points[:, 1] >= y_min) & (points[:, 1] <= y_max)):
        filtered_contours.append(cnt)
img = cv2.imread('./card/digitalCard.jpg')

print(len(filtered_contours))

25


In [89]:
new_filtered_contours = []
for cnt_in in filtered_contours:
    points = cnt_in.reshape(-1, 2)
    flag = False
    points = points.tolist()
    for cnt_out in filtered_contours:
        for point in points:
            if cv2.pointPolygonTest(cnt_out, point, False) > 0:
                flag = True
                break
    if not flag:
        new_filtered_contours.append(cnt_in)
print(len(new_filtered_contours))

16


In [90]:
box_contours = []
for cnt in new_filtered_contours:
    # 计算最小外接矩形（带旋转）
    rect = cv2.minAreaRect(cnt)
    box = cv2.boxPoints(rect)  # 获取四个顶点坐标
    box = np.intp(box)  # 转为整数
    box_contours.append(box)


print(len(box_contours))

16


In [91]:
box_contours = sorted(box_contours, key=lambda x: x[0][0])
card_croppeds = []
for idx, box in enumerate(box_contours):
    # 获取矩形框的轴对齐包围盒 (x, y, w, h)
    x, y, w, h = cv2.boundingRect(box)
    print(box)
    print(x)
    # 截取子图像
    cropped = card_t[y:y+h, x:x+w]
    card_croppeds.append(cropped)
    # 保存或显示

    #cv2.imshow(f'Box {idx}', cropped)
    #cv2.waitKey(0)
#cv2.destroyAllWindows()

[[ 50 198]
 [ 67 198]
 [ 67 227]
 [ 50 227]]
50
[[ 73 227]
 [ 73 198]
 [ 93 198]
 [ 93 227]]
73
[[100 227]
 [100 198]
 [119 198]
 [119 227]]
100
[[126 227]
 [126 198]
 [145 198]
 [145 227]]
126
[[179 227]
 [179 198]
 [198 198]
 [198 227]]
179
[[205 198]
 [224 198]
 [224 227]
 [205 227]]
205
[[231 198]
 [250 198]
 [250 227]
 [231 227]]
231
[[259 198]
 [276 198]
 [276 227]
 [259 227]]
259
[[309 227]
 [309 198]
 [328 198]
 [328 227]]
309
[[335 198]
 [354 198]
 [354 227]
 [335 227]]
335
[[361 198]
 [380 198]
 [380 227]
 [361 227]]
361
[[387 227]
 [387 198]
 [406 198]
 [406 227]]
387
[[440 198]
 [459 198]
 [459 227]
 [440 227]]
440
[[466 227]
 [466 198]
 [485 198]
 [485 227]]
466
[[492 227]
 [492 197]
 [511 197]
 [511 227]]
492
[[518 227]
 [518 198]
 [537 198]
 [537 227]]
518


In [92]:
print(len(contours_t))


16


In [93]:
filtered_contours_t = []
x_min, y_min, x_max, y_max = 2, 2, 6000, 2500
for cnt in contours_t:
    area = cv2.contourArea(cnt)
    points = cnt.reshape(-1, 2)
    if np.all((points[:, 0] >= x_min) & (points[:, 0] <= x_max) &
              (points[:, 1] >= y_min) & (points[:, 1] <= y_max)):
        filtered_contours_t.append(cnt)
new_filtered_contours_t = []
for cnt_in in filtered_contours_t:
    points = cnt_in.reshape(-1, 2)
    flag = False
    points = points.tolist()
    for cnt_out in filtered_contours_t:
        for point in points:
            if cv2.pointPolygonTest(cnt_out, point, False) > 0:
                flag = True
                break
    if not flag:
        new_filtered_contours_t.append(cnt_in)
print(len(new_filtered_contours_t))

10


In [94]:
box_contours_t = []
for cnt in new_filtered_contours_t:
    # 计算最小外接矩形（带旋转）
    rect = cv2.minAreaRect(cnt)
    box = cv2.boxPoints(rect)  # 获取四个顶点坐标
    box = np.intp(box)  # 转为整数
    box_contours_t.append(box)


print(len(box_contours_t))

10


In [95]:
box_contours_t = sorted(box_contours_t, key=lambda x: x[0][0])
template_croppeds = []
for idx, box in enumerate(box_contours_t):
    # 获取矩形框的轴对齐包围盒 (x, y, w, h)
    x, y, w, h = cv2.boundingRect(box)
    print(box)
    print(x)
    # 截取子图像
    cropped = template_t[y:y+h, x:x+w]
    template_croppeds.append(cropped)
    # 保存或显示




[[ 9 87]
 [ 9 10]
 [59 10]
 [59 87]]
9
[[ 80  87]
 [ 80  10]
 [130  10]
 [130  87]]
80
[[151  87]
 [151  10]
 [200  10]
 [200  87]]
151
[[221  87]
 [221  10]
 [271  10]
 [271  87]]
221
[[297  87]
 [297  10]
 [342  10]
 [342  87]]
297
[[363  87]
 [363  10]
 [412  10]
 [412  87]]
363
[[433  87]
 [433  10]
 [483  10]
 [483  87]]
433
[[504  87]
 [504  10]
 [554  10]
 [554  87]]
504
[[575  87]
 [575  10]
 [624  10]
 [624  87]]
575
[[645  87]
 [645  10]
 [695  10]
 [695  87]]
645


In [96]:
indexes = []
for cropped in card_croppeds:
    best_score = -1000
    best_idx = -1
    for idx, template_cropped in enumerate(template_croppeds):
        template_cropped_reshape = cv2.resize(template_cropped, (cropped.shape[1], cropped.shape[0]), interpolation=cv2.INTER_AREA)
        result = cv2.matchTemplate(cropped, template_cropped_reshape, cv2.TM_CCORR_NORMED)
        _, max_val, _, _ = cv2.minMaxLoc(result)
        if max_val > best_score:
            best_score = max_val
            best_idx = idx
    print(best_idx)
    indexes.append(best_idx)

    

4
0
0
0
1
2
3
4
5
6
7
8
9
0
1
0


In [97]:
print(indexes)

[4, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 0]
