In [28]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import imutils

In [29]:
card = cv2.imread('./card/digitalCard.jpg')
template = cv2.imread('./card/digitalTemplate.jpg')
card = cv2.cvtColor(card, cv2.COLOR_BGR2GRAY)
template = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)


In [30]:
_, card_t = cv2.threshold(card, 127, 255, cv2.THRESH_BINARY_INV)

In [31]:
contours_c, hierarchy_c = cv2.findContours(card_t, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)


In [32]:
_, template_t = cv2.threshold(template, 10, 255, cv2.THRESH_BINARY)
contours_t, hierarchy_t = cv2.findContours(template_t, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)



In [33]:
filtered_contours = []
x_min, y_min, x_max, y_max = 0, 100, 600, 250
for cnt in contours_c:
    area = cv2.contourArea(cnt)
    points = cnt.reshape(-1, 2)
    if np.all((points[:, 0] >= x_min) & (points[:, 0] <= x_max) &
              (points[:, 1] >= y_min) & (points[:, 1] <= y_max)):
        filtered_contours.append(cnt)
img = cv2.imread('./card/digitalCard.jpg')

print(len(filtered_contours))

25


In [34]:
new_filtered_contours = []
for cnt_in in filtered_contours:
    points = cnt_in.reshape(-1, 2)
    flag = False
    points = points.tolist()
    for cnt_out in filtered_contours:
        for point in points:
            if cv2.pointPolygonTest(cnt_out, point, False) > 0:
                flag = True
                break
    if not flag:
        new_filtered_contours.append(cnt_in)
print(len(new_filtered_contours))

16


In [35]:
box_contours = []
for cnt in new_filtered_contours:
    # 计算最小外接矩形（带旋转）
    rect = cv2.minAreaRect(cnt)
    box = cv2.boxPoints(rect)  # 获取四个顶点坐标
    box = np.intp(box)  # 转为整数
    box_contours.append(box)


print(len(box_contours))

16


In [36]:
sorted(box_contours, key=lambda x: x[0][0])
card_croppeds = []
for idx, box in enumerate(box_contours):
    # 获取矩形框的轴对齐包围盒 (x, y, w, h)
    x, y, w, h = cv2.boundingRect(box)
    print(box)
    print(x)
    # 截取子图像
    cropped = card_t[y:y+h, x:x+w]
    card_croppeds.append(cropped)
    # 保存或显示
    cv2.imwrite(f'cropped_{idx}.jpg', cropped)
    cv2.imshow(f'Box {idx}', cropped)
    cv2.waitKey(0)
cv2.destroyAllWindows()

[[518 227]
 [518 198]
 [537 198]
 [537 227]]
518
[[466 227]
 [466 198]
 [485 198]
 [485 227]]
466
[[440 198]
 [459 198]
 [459 227]
 [440 227]]
440
[[387 227]
 [387 198]
 [406 198]
 [406 227]]
387
[[361 198]
 [380 198]
 [380 227]
 [361 227]]
361
[[335 198]
 [354 198]
 [354 227]
 [335 227]]
335
[[309 227]
 [309 198]
 [328 198]
 [328 227]]
309
[[259 198]
 [276 198]
 [276 227]
 [259 227]]
259
[[231 198]
 [250 198]
 [250 227]
 [231 227]]
231
[[205 198]
 [224 198]
 [224 227]
 [205 227]]
205
[[179 227]
 [179 198]
 [198 198]
 [198 227]]
179
[[126 227]
 [126 198]
 [145 198]
 [145 227]]
126
[[100 227]
 [100 198]
 [119 198]
 [119 227]]
100
[[ 73 227]
 [ 73 198]
 [ 93 198]
 [ 93 227]]
73
[[ 50 198]
 [ 67 198]
 [ 67 227]
 [ 50 227]]
50
[[492 227]
 [492 197]
 [511 197]
 [511 227]]
492
